name: UnlimitedPlayers
version: ${project.version}
author: Greenlio
description: Allows server owners to use MH10 and have unlimited players!
api-version: 1.13
main: dev.greenlio.unlimitedplayers.UnlimitedPlayers
commands:
  setslots:
    description: Change the max players on the server
    usage: /<command> <slots>
    aliases: [unlimitedplayers]
